name: Build and push Docker image

on:
  # For the manual run.
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/build-image/**'
      - '.github/workflows/docker-build-image.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/build-image/**'
      - '.github/workflows/docker-build-image.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker image for KNP build
        uses: docker/build-push-action@v6
        env:
          DOCKERHUB_LOGIN: ${{ vars.DOCKERHUB_LOGIN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:docker/build-image"
          load: true
          push: true
          tags: $DOCKERHUB_LOGIN/knp-build-image:latest
          timeout-minutes: 180
          continue-on-error: false
