name: Build and push Docker image

on:
  # For the manual run.
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/build-image/**'
      - '.github/workflows/docker-build-image.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/build-image/**'
      - '.github/workflows/docker-build-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build and push the Docker image for KNP build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/build-image"
          push: true
          tags: ${{ vars.DOCKERHUB_LOGIN }}/knp-build-image:latest
          timeout-minutes: 180
          continue-on-error: false
